3-1. 네이버 책 검색 API 호출하기 (필수)

https://developers.naver.com/docs/serviceapi/search/book/book.md#%EC%B1%85

검색어(query)는  함수의 인자로 받아서 동적으로 처리 되어야 합니다. 

최대한 코드가 중복되지 않도록 공통으로 처리해야 하는 부분은 함수로 작성해서 재사용 하는 방식으로 코드를 작성해 주세요.
```
def search_books(query):   
    # query string 문자열을 dict 선언
    payload = {
    'query':  query, #'파이썬',
    'display': 50,
    'sort': 'sim'
    }

   url = 'https://openapi.naver.com/v1/search/book.json'
   
   # requests get(url, params, headers) 요청 
   res = requests.get(url, params=payload, headers=headers)
   # json() 함수로 응답 결과 가져오기
   items_data = res.json()['items'] 
```

1. 질문 :  검색어로  찾은  책 목록을 json 파일로 저장하기

   data/books.json 파일로 저장해 주세요.

2. books.json 파일을 Pandas DataFrame로 저장하기

3. 질문 :  검색어로  찾은  책 목록 출력하기

출력결과 : 



4. 질문 :  검색어로  찾은  책 목록 중에서 가격이 2만원 이상인 책만 출력하기

title,author,discount,publisher,pubdate 컬럼만 출력
가격은 descending (내림차순), index 초기화


6. 질문 :  검색어로  찾은  책 목록 중에서 출판사가 인피니티북스인 책만 출력하기

image , description 컬럼은 제외한 모든 컬럼 출력하기
index 는 초기화

In [ ]:
import requests
from dotenv import load_dotenv
import os
import pandas as pd
import json

def search_books(query):   
    # query string 문자열을 dict 선언
    payload = {
    'query':  query, #'파이썬',
    'display': 50,
    'sort': 'sim'
    }

    # .env 파일에서 환경 변수 로드
    load_dotenv()

    # 환경 변수에서 값 읽기
    client_id = os.getenv("NAVER_CLIENT_ID")  # .env 파일의 NAVER_CLIENT_ID
    client_secret = os.getenv("NAVER_CLIENT_SECRET")  # .env 파일의 NAVER_CLIENT_SECRET

    headers = {
        'X-Naver-Client-Id': client_id,
        'X-Naver-Client-Secret': client_secret,
    }
    url = 'https://openapi.naver.com/v1/search/book.json'
    
    # requests get(url, params, headers) 요청 
    res = requests.get(url, params=payload, headers=headers)
    # json() 함수로 응답 결과 가져오기
    items_data = res.json()['items']
    
    # 1. 질문 :  검색어로  찾은  책 목록을 json 파일로 저장하기 data/books.json 파일로 저장해 주세요.
    if not os.path.exists('data'):
        os.makedirs('data')
    with open('data/books.json', 'w', encoding='utf-8') as f:
        # json.dumps() 함수로 json 파일로 저장하기
        f.write(json.dumps(items_data, ensure_ascii=False, indent=4))

    # 2. books.json 파일을 Pandas DataFrame로 저장하기
    df = pd.read_json('data/books.json')

    # 3. 질문 :  검색어로  찾은  책 목록 출력하기
    display(df)

    # 4. 질문 :  검색어로  찾은  책 목록 중에서 가격이 2만원 이상인 책만 출력하기
    # title,author,discount,publisher,pubdate 컬럼만 출력
    # 가격은 descending (내림차순), index 초기화
    df2 = df[df['discount'] >= 20000][['title','author','discount','publisher','pubdate']].sort_values(by='discount', ascending=False).reset_index(drop=True)
    display(df2)
    # 6. 질문 :  검색어로  찾은  책 목록 중에서 출판사가 인피니티북스인 책만 출력하기
    # image , description 컬럼은 제외한 모든 컬럼 출력하기
    #index 는 초기화
    df3 = df[df['publisher'] == '인피니티북스'].drop(columns=['image', 'description']).reset_index(drop=True)
    display(df3)

search_books('파이썬')

,title,link,author,discount,publisher,pubdate,isbn
0,파이썬,https://search.shopping.naver.com/book/catalog...,천인국,12000,인피니티북스,20170830,9791185578330
1,파이썬 플러스,https://search.shopping.naver.com/book/catalog...,최희식,23750,인피니티북스,20240731,9791192373362
2,디딤돌 파이썬 (구조적 프로그래밍으로 설명한 파이썬 기초),https://search.shopping.naver.com/book/catalog...,이찬수,26100,인피니티북스,20220823,9791192373058

3-2. 네이버 쇼핑 검색 API 호출하기 (필수)
https://developers.naver.com/docs/serviceapi/search/book/book.md#%EC%B1%85

검색어(query)는  함수의 인자로 받아서 동적으로 처리되어야 합니다. 
최대한 코드가 중복되지 않도록 공통으로 출력되는 부분은 함수로 처리해야 합니다.

def search_shops(query):

    payload = {
    'query':  query, #'가디건',
    'display': 50,
    'sort': 'sim'
    }

   url = 'https://openapi.naver.com/v1/search/shop.json'
   
   # requests get(url, params, headers) 요청 
   res = requests.get(url, params=payload, headers=headers)
   # json() 함수로 응답 결과 가져오기
   items_data = res.json()['items']


2. shops.json 파일을 Pandas DataFrame로 저장하기

3. 질문 :  검색어로  찾은  Shop의 상품  목록 출력하기


4. 질문 :  검색어로  찾은  Shop의 상품  목록 중에서 가격이 50,000원 이하인 상품만 출력하기
brand,lprice,mallName,link 컬럼만 출력
가격은 ascending (오름차순), index 초기화


4. 질문 :  검색어로  찾은  Shop의 상품  목록 중에서 특정 쇼핑몰 상품만 출력하기
lprice 부터 brand  컬럼까지 slicing 으로 선택하여 출력
가격은 ascending (오름차순), index 초기화

In [ ]:
import requests
from dotenv import load_dotenv
import os
import pandas as pd
import json

def search_shops(query):
    load_dotenv()

    # 환경 변수에서 값 읽기
    client_id = os.getenv("NAVER_CLIENT_ID")  # .env 파일의 NAVER_CLIENT_ID
    client_secret = os.getenv("NAVER_CLIENT_SECRET")  # .env 파일의 NAVER_CLIENT_SECRET

    headers = {
        'X-Naver-Client-Id': client_id,
        'X-Naver-Client-Secret': client_secret,
    }
    
    payload = {
    'query':  query, #'가디건',
    'display': 50,
    'sort': 'sim'
    }
    url = 'https://openapi.naver.com/v1/search/shop.json'
   
   # requests get(url, params, headers) 요청 
    res = requests.get(url, params=payload, headers=headers)
    res.raise_for_status()  # HTTPError 발생 시 예외 처리
    items_data = res.json()['items']
    if not os.path.exists('data'):
        os.makedirs('data')
    with open('data/shops.json', 'w', encoding='utf-8') as f:
        # json.dumps() 함수로 json 파일로 저장하기
        f.write(json.dumps(items_data, ensure_ascii=False, indent=4))
    # 2. shops.json 파일을 Pandas DataFrame로 저장하기
    df = pd.read_json('data/shops.json')
    # 3. 질문 :  검색어로  찾은  Shop의 상품  목록 출력하기
    display(df)

    # 4. 질문 :  검색어로  찾은  Shop의 상품  목록 중에서 가격이 50,000원 이하인 상품만 출력하기
    # brand,lprice,mallName,link 컬럼만 출력
    # 가격은 ascending (오름차순), index 초기화
    df2 = df[df['lprice'] <= 50000][['brand','lprice','mallName','link']].sort_values(by='lprice', ascending=True).reset_index(drop=True)
    display(df2)

    # 4. 질문 :  검색어로  찾은  Shop의 상품  목록 중에서 특정 쇼핑몰 상품만 출력하기
    # lprice 부터 brand  컬럼까지 slicing 으로 선택하여 출력
    # 가격은 ascending (오름차순), index 초기화
    df3 = df[df['mallName']=='네이버'].loc[:,'lprice':'brand'].sort_values(by='lprice', ascending=True).reset_index(drop=True)
    display(df3)

search_shops('가디건')

,brand,lprice,mallName,link
0,H&M,17512,네이버,https://search.shopping.naver.com/catalog/5178...
1,,18900,코이블리,https://smartstore.naver.com/main/products/482...
2,,18900,코이블리,https://smartstore.naver.com/main/products/438...
3,,19800,로이앤한나,https://smartstore.naver.com/main/products/490...
4,,19900,ARUMY,https://smartstore.naver.com/main/products/546...
5,리스트,23000,네이버,https://search.shopping.naver.com/catalog/5114...
6,,23900,고고하니,https://smartstore.naver.com/main/products/559...
7,,24800,베이지블랑.,https://smartstore.naver.com/main/products/519...
8,,24900,ARUMY,https://smartstore.naver.com/main/products/995...
9,,27000,건강한생활82,https://smartstore.naver.com/main/products/798...
10,비비안웨스트우드,28070,네이버,https://search.shopping.naver.com/catalog/4347...
11,,29800,미드시티 여성니트,https://smartstore.naver.com/main/products/100...
12,,29900,지읒이응,https://smartstore.naver.com/main/products/539...
13,제너럴아이디어,31416,네이버,https://search.shopping.naver.com/catalog/4954...
14,제너럴아이디어,32400,네이버,https://search.shopping.naver.com/catalog/5328...
15,쉬즈미스,36910,네이버,https://search.shopping.naver.com/catalog/4962...
16,모르간,37160,네이버,https://search.shopping.naver.com/catalog/5050...
17,벤시몽,37650,네이버,https://search.shopping.naver.com/catalog/5337...
18,,39800,왓위웨어,https://smartstore.naver.com/main/products/529...
19,제이플로우,41800,제이플로우,https://smartstore.naver.com/main/products/810...
20,,42000,ttoyuni,https://smartstore.naver.com/main/products/904...
21,사색,43700,사색,https://smartstore.naver.com/main/products/113...
22,벤시몽,44910,네이버,https://search.shopping.naver.com/catalog/5323...
23,,49500,루나드엘,https://smartstore.naver.com/main/products/997...
24,유니클로,49800,더헤르츠,https://smartstore.naver.com/main/products/100...

    lprice hprice mallName    productId  productType     brand
0    17512             네이버  51781610172            1       H&M
1    23000             네이버  51143733510            1       리스트
2    28070             네이버  43475137325            1  비비안웨스트우드
3    31416             네이버  49541497760            1   제너럴아이디어
4    32400             네이버  53287208769            1   제너럴아이디어
5    36910             네이버  49625464649            1      쉬즈미스
6    37160             네이버  50504636053            1       모르간
7    37650             네이버  53373694627            1       벤시몽
8    44910             네이버  53232763110            1       벤시몽
9    53900             네이버  53020866519            1    셀렙샵에디션
10   80100             네이버  49714141886            1      라코스테
11  174090             네이버  50705955349            1      라코스테